services:
  blog-app-jenkins:
    image: blog-app-jenkins
    ports:
      - "3001:5173"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    container_name: blog-app-jenkins
