version: '3.8'

services:
  blog-app-jenkins:
    build: .
    ports:
      - "3001:5173"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped
    container_name: blog-app-jenkins
